services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
      - .env.production
    volumes:
      - next-cache:/app/.next/cache
    networks:
      - caddy
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 1.5G
        reservations:
          cpus: '0.5'
          memory: 768M
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/api/health"]
      interval: 60s 
      timeout: 3s    
      retries: 2     
      start_period: 30s  

networks:
  caddy:
    external: true