# Base image
FROM node:22.12.0-alpine

# Install dependencies
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies
COPY package.json pnpm-lock.yaml* ./
RUN corepack enable pnpm && pnpm install

# Copy source code
COPY . .

# Set environment variables for development
ENV NODE_ENV=development

EXPOSE 3000

ENV PORT=3000

# Run the Next.js development server
ENV HOSTNAME=0.0.0.0
CMD ["pnpm", "dev"]
