services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - NEXT_PUBLIC_API_URL=http://catcident-backend-api-1:8000
    command: pnpm dev
    env_file:
      - .env
      - .env.development
    volumes:
      - .:/app
      - /app/node_modules
      - next-cache:/app/.next/cache
    tmpfs:
      - /app/tmp:exec,uid=1001,gid=1001,mode=1777,size=256m
    networks:
      - caddy
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 3s
      retries: 2
      start_period: 20s
    restart: unless-stopped

volumes:
  next-cache:
    name: ${COMPOSE_PROJECT_NAME:-nextjs}_next-cache

networks:
  caddy:
    external: true