# Base image
FROM node:22.14.0-alpine

# Install dependencies
RUN apk add --no-cache libc6-compat curl
WORKDIR /app

# 비root 사용자 생성
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# 필요한 디렉토리 생성 및 권한 설정
RUN mkdir -p /app/.next/cache && \
    mkdir -p /app/tmp && \
    chown -R nextjs:nodejs /app

# Install dependencies
COPY package.json pnpm-lock.yaml* ./
RUN corepack enable pnpm && pnpm install

# Copy source code
COPY --chown=nextjs:nodejs . .

# Set environment variables for development
ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

USER nextjs

# Run the Next.js development server
CMD ["pnpm", "dev"]
